install.packages("shiny",repos="https://cloud.r-project.org")
install.packages("shinythemes",repos="https://cloud.r-project.org")
install.packages("shinydashboard",repos="https://cloud.r-project.org")
install.packages("units",repos="https://cloud.r-project.org",type="source",configure.args = "--with-udunits2-include=/usr/share/xml/udunits")
# install.packages("geos",repos="https://cloud.r-project.org")
# install.packages("rgdal",repos="https://cloud.r-project.org")
# install.packages("PROJ",repos="https://cloud.r-project.org")
#install.packages("classInt",repos="https://cloud.r-project.org")
install.packages("sf",repos="https://cloud.r-project.org",type="source",configure.args = "--with-udunits2-include=/usr/share/xml/udunits")
install.packages("mapview",repos="https://cloud.r-project.org")
install.packages("leaflet",repos="https://cloud.r-project.org")
install.packages("leafpop",repos="https://cloud.r-project.org")
#install.packages("remotes",repos="https://cloud.r-project.org")
install.packages("devtools",repos="https://cloud.r-project.org")
# devtools::install_github("RStudio/shiny")
# devtools::install_github("RStudio/shinythemes")
# devtools::install_github("RStudio/shinydashboard")
# devtools::install_github("r-spatial/sf")
# devtools::install_github("r-spatial/mapview")
# devtools::install_github("r-spatial/leaflet")
# devtools::install_github("r-spatial/leafpop")

